# Generated by Django 6.0 on 2025-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAGBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hf_api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_model_id', models.CharField(default='mistralai/Mistral-7B-Instruct-v0.2', max_length=100)),
                ('embedding_model_id', models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=100)),
                ('system_prompt', models.TextField(default="You are a helpful assistant. Answer the user's question using only the provided context.")),
                ('document', models.FileField(blank=True, null=True, upload_to='training_docs/')),
                ('collection_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
