# Generated by Django 5.2.4 on 2025-12-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragbot',
            name='avatar',
            field=models.CharField(default='🤖', max_length=255),
        ),
    ]
