# Generated by Django 5.2.4 on 2025-12-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_ragbot_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAGBot',
        ),
    ]
